@extends('com.layout')
@section('title')
All Created Profiles
@endsection
@section('body')


    <div class="md-card ">

        <div class="md-card-content">
            <div class="uk-grid" data-uk-grid-margin="">
                <div class="uk-width-medium-1-1 ">
                    <div class="uk-width-medium-1-1 uk-row-first">
                    {{--     @if(session()->has('done'))
                            <div class="alert alert-success">
                                <div class="uk-alert uk-alert-success" data-uk-alert="">
                                    <a href="#" class="uk-alert-close uk-close"></a>
                                    {{ session()->get('done') }}
                                </div>
                            </div>
                        @endif

                        @if(count($errors) > 0)
                            @foreach ($errors->all() as $error)
                                <div class="uk-alert uk-alert-danger" data-uk-alert="">
                                    <a href="#" class="uk-alert-close uk-close"></a>
                                    {{$error}}
                                </div>
                            @endforeach
                        @endif
                    </div> --}}
                    <div class="uk-grid">
                        <div class="uk-width-large-1-1 uk-width-medium-1-1">
                            <table id="dt_individual_search" class="uk-table uk-table-bordered uk-table-hover" style="width: 100%">
                                <thead>
                                <tr>
                                    <th width="40">#</th>
                                    <th>Generated By</th>
                                    <th>Category</th>
                                    <th>File Name</th>
                                    <th>Email_File_Name</th>
                                    <th>Title</th>
                                    <th>Client Name</th>
                                    {{-- <th>SR_NO</th> --}}
                                    <th>Date&Time</th>
                                    <th>Due Date</th>
                                    <th>Action</th>
                                </tr>
                                </thead>
                                <tbody>
                                    <?php $j=1; ?>
                                @foreach($files as $i)

                                    <tr>
                                        <td>{{$j}}</td>
                                        <td>{{$i->user_name}}</td>
                                        <td>{{$i->dropdown}}</td>
                                        {{-- <td><a href="/mergedownload/{{$i->name}}.pdf" title="Click to download">{{$i->name}}</a></td> --}}
                                        @if ($i->email_name !="")
<?php                                           
$a=json_decode($i->name);

?>      
<td style="width: 10%;">
@foreach ( $a  as $e)
            <a href="/mergedownload/{{$e}}" title="Click to download">{{$e}}</a><br>  
        @endforeach
        </td>
                                        @else
                                        <td><a href="/mergedownload/{{$i->name}}.pdf" title="Click to download">{{$i->name}}</a></td>

                                        @endif
                                        <td><a href="/mergedownload/{{$i->email_name}}" title="Click to download">{{$i->email_name}}</a></td>
                                        <td>{{$i->title}}</td>
                                        <td>{{$i->client_name}}</td>
                                        {{-- <td>{{$i->sr_no}}</td> --}}
                                        <td>{{$i->date}}</td>
                                        <td>{{$i->due_date}}</td>
                                        <td> <button class="uk-button-success" onclick="moveback('{{$i->id}}',$(this))">Move Back</button>
                                                   <button class="uk-button-danger" onclick="destroy('{{$i->id}}','this profile')" >Delete</button>
                                               </td>
                                        <td>
                                        
                                    </tr>
                                    <?php  $j++; ?>
                                @endforeach


                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>




<script>


    {{--function storeDirectory() {--}}
        {{--$.ajax({--}}
            {{--url:"/directory/new",--}}
            {{--type:"post",--}}
            {{--data:{_token: '{{csrf_token()}}', name:$("#name").val()},--}}
            {{--complete:function (e) {console.log(e);selectDirectory();}--}}
        {{--});--}}

    {{--}--}}


    {{--function selectDirectory() {--}}
        {{--$.ajax({--}}
            {{--url:"/directory/select",--}}
            {{--type:"get",--}}
        {{--complete:function (e) {--}}
        {{--console.log(e);--}}
        {{--var json = JSON.parse(e.responseText);--}}
        {{--$.each(json,function (a,b) {--}}
            {{--$("#list").append('' +--}}
                {{--'<tr>' +--}}
                {{--'<td>'+b["id"]+'</td>' +--}}
                {{--'<td>'+b["name"]+'</td>' +--}}
                {{--'<td></td>' +--}}
                {{--'</tr>');--}}

            {{--console.log();--}}

        {{--})--}}

            {{--}--}}
        {{--});--}}

    {{--}--}}

</script>
@endsection


@section('scripts')
<script src="/public_assets/bower_components/datatables/media/js/jquery.dataTables.min.js"></script>
<script src="/public_assets/bower_components/datatables-buttons/js/dataTables.buttons.js"></script>
<script src="/public_assets/assets/js/custom/datatables/buttons.uikit.js"></script>
<script src="/public_assets/bower_components/jszip/dist/jszip.min.js"></script>
<script src="/public_assets/bower_components/pdfmake/build/pdfmake.min.js"></script>
<script src="/public_assets/bower_components/pdfmake/build/vfs_fonts.js"></script>
<script src="/public_assets/bower_components/datatables-buttons/js/buttons.colVis.js"></script>
<script src="/public_assets/bower_components/datatables-buttons/js/buttons.html5.js"></script>
<script src="/public_assets/bower_components/datatables-buttons/js/buttons.print.js"></script>
<script src="/public_assets/assets/js/custom/datatables/datatables.uikit.min.js"></script>
<script src="/public_assets/assets/js/pages/plugins_datatables.min.js"></script>

<script>
    function destroy(id,name) {
        var r = confirm("Delete " + name);
        if (r == true) {
            window.location="/merged/delete/"+id;
        }
    }
    function moveback(id,elm){
        
        $.ajax({
               type:'GET',
               url:'/merged_archive_back',
               data:{"id": id},
               success:function(response){
                  console.log(response);
                  elm.closest('tr').remove();
               }
            });
    }
</script>

@endsection
